CREATE TABLE IF NOT EXISTS tx_empresas (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    logo_url VARCHAR(255) NULL,
    ciudad VARCHAR(80) NOT NULL,
    config JSON NULL,
    modo_despacho_default ENUM('AUTOMATICO','HIBRIDO','MANUAL') NOT NULL DEFAULT 'HIBRIDO',
    activa TINYINT(1) NOT NULL DEFAULT 1,
    creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
