CREATE TABLE IF NOT EXISTS tx_vehiculos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT UNSIGNED NOT NULL,
    numero_interno VARCHAR(20) NOT NULL,
    placa VARCHAR(10) NOT NULL,
    tipo VARCHAR(60) NOT NULL DEFAULT 'TAXI',
    estado_vehiculo ENUM('DISPONIBLE','SOLICITADO','EN_SERVICIO','EN_TURNO','FUERA_DE_TURNO','NO_DISPONIBLE','PENDIENTE_CONFIRMACION') NOT NULL DEFAULT 'FUERA_DE_TURNO',
    creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_tx_vehiculos_empresa_placa (empresa_id, placa),
    CONSTRAINT fk_tx_vehiculos_empresa FOREIGN KEY (empresa_id) REFERENCES tx_empresas (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
