CREATE TABLE IF NOT EXISTS tx_carreras (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT UNSIGNED NOT NULL,
    linea_id INT UNSIGNED NOT NULL,
    conversacion_ref VARCHAR(191) NOT NULL,
    cliente_id INT UNSIGNED NOT NULL,
    tipo_servicio VARCHAR(60) NOT NULL,
    recogida_texto VARCHAR(255) NOT NULL,
    recogida_lat DECIMAL(10,7) NULL,
    recogida_lng DECIMAL(10,7) NULL,
    destino_texto VARCHAR(255) NOT NULL,
    destino_lat DECIMAL(10,7) NULL,
    destino_lng DECIMAL(10,7) NULL,
    observaciones TEXT NULL,
    estado ENUM('RECIBIDA','DATOS_COMPLETOS','EN_DESPACHO','CANDIDATOS_PROPUESTOS','ASIGNADA','ACEPTADA','RECHAZADA','EN_CAMINO','EN_SERVICIO','FINALIZADA','CANCELADA','NO_ATENDIDA') NOT NULL DEFAULT 'RECIBIDA',
    modo_despacho_usado ENUM('AUTOMATICO','HIBRIDO','MANUAL') NOT NULL,
    vehiculo_id INT UNSIGNED NULL,
    conductor_id INT UNSIGNED NULL,
    motivo_cierre VARCHAR(255) NULL,
    creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    asignada_en DATETIME NULL,
    finalizada_en DATETIME NULL,
    idempotencia_hash VARCHAR(64) NOT NULL,
    UNIQUE KEY uq_tx_carreras_idempotencia (idempotencia_hash),
    CONSTRAINT fk_tx_carreras_empresa FOREIGN KEY (empresa_id) REFERENCES tx_empresas (id),
    CONSTRAINT fk_tx_carreras_linea FOREIGN KEY (linea_id) REFERENCES tx_lineas (id),
    CONSTRAINT fk_tx_carreras_cliente FOREIGN KEY (cliente_id) REFERENCES tx_clientes (id),
    CONSTRAINT fk_tx_carreras_vehiculo FOREIGN KEY (vehiculo_id) REFERENCES tx_vehiculos (id),
    CONSTRAINT fk_tx_carreras_conductor FOREIGN KEY (conductor_id) REFERENCES tx_conductores (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
