CREATE TABLE IF NOT EXISTS tx_usuarios (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT UNSIGNED NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    usuario VARCHAR(120) NOT NULL,
    clave_hash VARCHAR(255) NOT NULL,
    rol ENUM('RADIOOPERADOR','ADMIN') NOT NULL DEFAULT 'RADIOOPERADOR',
    activo TINYINT(1) NOT NULL DEFAULT 1,
    creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_tx_usuarios_usuario (usuario),
    CONSTRAINT fk_tx_usuarios_empresa FOREIGN KEY (empresa_id) REFERENCES tx_empresas (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
